version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Run Maven
          command: mvn clean test verify

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # N'exécute le pipeline que sur la branche master
