version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:*
      - image: circleci/openjdk:17-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Setup Maven
          command: |
            mvn -version
            java -version
      - run:
          name: Execute Maven tests
          command: mvn clean test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report
      - codecov/report:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload
